on:
  workflow_dispatch:

jobs:
  fetch_tags:
    runs-on: ubuntu-latest
    
    outputs:
      nginx_tag: ${{ steps.step_fetch_nginx_tag.outputs.tag }}
      more_module_tag: ${{ steps.step_fetch_more_module_tag.outputs.tag }}
    
    steps:
      - id: step_fetch_nginx_tag
        name: Get nginx latest tag
        run: |
          nginx_tag=$(curl --silent "https://api.github.com/repos/nginx/nginx/tags" | grep -Po "(?<=\"name\": \").*(?=\")" | head -n 1)
          echo "tag=$nginx_tag" >> "$GITHUB_OUTPUT"

      - id: step_fetch_more_module_tag
        name: Get nginx more module latest tag
        run: |
          more_tag=$(curl --silent "https://api.github.com/repos/openresty/headers-more-nginx-module/tags" | grep -Po "(?<=\"name\": \").*(?=\")" | head -n 1)
          echo "tag=$more_tag" >> "$GITHUB_OUTPUT"

      - id: output_tag
        name: Generate output tag
        run: |
          part1=$(sed "s/release-//g" <<< "${{steps.step_fetch_nginx_tag.outputs.tag}}")
          more_tag="${{steps.step_fetch_more_module_tag.outputs.tag}}"
          part2=${more_tag:1}
          output_tag="n_$part1-m_$part2"
          echo "Output tag: $output_tag"
          echo "tag=$output_tag" >> "$GITHUB_OUTPUT"

      - id: checkTag
        uses: mukunku/tag-exists-action@v1.4.0
        with: 
          tag: ${{ steps.output_tag.outputs.tag }}

      - id: test_output
        name: Step to test output
        env:
          NGINX_TAG: ${{steps.step_fetch_nginx_tag.outputs.tag}}
          MORE_TAG: ${{steps.step_fetch_more_module_tag.outputs.tag}}
          OUTPUT_TAG: ${{steps.step_fetch_more_module_tag.outputs.tag}}
        run: |
          echo "nginx: $NGINX_TAG; more_module: $MORE_TAG"
          echo "Output tag: $OUTPUT_TAG"
          echo "Output tag exists: ${{ steps.checkTag.outputs.exists }}"
  
  build:
    runs-on: ubuntu-latest

    needs: fetch_tags
    steps:
      - name: Show paths
        run: |
          echo "HOME: $HOME"
          echo "pwd: $(pwd)"
          echo "github workspace: $GITHUB_WORKSPACE"
      
      - id: step_setup_gcc
        uses: egor-tensin/setup-gcc@v1

      - id: step_checkout_nginx
        uses: actions/checkout@v2
        with:
          repository: nginx/nginx
          path: './nginx'
          ref: ${{needs.fetch_tags.outputs.nginx_tag}}

      - id: step_checkout_more_module
        uses: actions/checkout@v2
        with:
          repository: openresty/headers-more-nginx-module
          path: './more_module'
          ref: ${{needs.fetch_tags.outputs.more_module_tag}}
      
      - id: build
        run: |
          cd "$GITHUB_WORKSPACE/nginx"
          output_path="$GITHUB_WORKSPACE/nginx_output"
          ./auto/configure --prefix="$output_path" --add-dynamic-module=../more_module --with-compat
          make install
          
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/nginx_output

          echo "load_module modules/ngx_http_js_module.so;" >> /tmp/nginx.conf
          cat $output_path/conf/nginx.conf >> /tmp/nginx.conf
          mv /tmp/nginx.conf $output_path/
          cd $output_path/sbin
          ./nginx -T
      - id: upload_module
        name: Upload output module
        
        
      - id: test_output
        name: Step to test output
        run: |
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/nginx_output


          
    
