on:
  workflow_dispatch:
    inputs:
      nginx_tag:
        description: 'Nginx tag'
        type: string
      more_module_tag:
        description: 'Nginx more module tag'
        type: string
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday UTC 00:00

jobs:
  fetch_tags:
    runs-on: ubuntu-latest
    
    outputs:
      nginx_tag: ${{ inputs.nginx_tag || steps.step_fetch_nginx_tag.outputs.tag }}
      more_module_tag: ${{ inputs.more_module_tag || steps.step_fetch_more_module_tag.outputs.tag }}
      output_tag: ${{steps.output_tag.outputs.tag}}
      output_tag_exists: ${{ steps.check_tag.outputs.exists }}
    
    steps:
      - id: step_fetch_nginx_tag
        name: Get nginx latest tag
        run: |
          nginx_tag=$(curl --silent "https://api.github.com/repos/nginx/nginx/tags" | grep -Po "(?<=\"name\": \").*(?=\")" | head -n 1)
          echo "tag=$nginx_tag" >> "$GITHUB_OUTPUT"

      - id: step_fetch_more_module_tag
        name: Get nginx more module latest tag
        run: |
          more_tag=$(curl --silent "https://api.github.com/repos/openresty/headers-more-nginx-module/tags" | grep -Po "(?<=\"name\": \").*(?=\")" | head -n 1)
          echo "tag=$more_tag" >> "$GITHUB_OUTPUT"

      - id: output_tag
        name: Generate output tag
        run: |
          part1=$(sed "s/release-//g" <<< "${{ inputs.nginx_tag || steps.step_fetch_nginx_tag.outputs.tag}}")
          more_tag="${{ inputs.more_module_tag || steps.step_fetch_more_module_tag.outputs.tag }}"
          part2=${more_tag:1}
          output_tag="n_$part1-m_$part2"
          echo "Output tag: $output_tag"
          echo "tag=$output_tag" >> "$GITHUB_OUTPUT"

      - id: check_tag
        uses: mukunku/tag-exists-action@v1.4.0
        with: 
          tag: ${{ steps.output_tag.outputs.tag }}

      - id: test_output
        name: Step to test output
        env:
          NGINX_TAG: ${{steps.step_fetch_nginx_tag.outputs.tag}}
          MORE_TAG: ${{steps.step_fetch_more_module_tag.outputs.tag}}
          OUTPUT_TAG: ${{steps.output_tag.outputs.tag}}
        run: |
          echo "nginx: $NGINX_TAG; more_module: $MORE_TAG"
          echo "Output tag: $OUTPUT_TAG"
          echo "Output tag exists: ${{ steps.check_tag.outputs.exists }}"
  
  build:
    runs-on: ubuntu-latest
    needs: fetch_tags
    if: ${{ needs.fetch_tags.outputs.output_tag_exists == 'false' }}

    steps:
      - name: Show paths
        run: |
          echo "HOME: $HOME"
          echo "pwd: $(pwd)"
          echo "github workspace: $GITHUB_WORKSPACE"
      
      - id: step_setup_gcc
        uses: egor-tensin/setup-gcc@v1

      - id: step_checkout_nginx
        uses: actions/checkout@v2
        with:
          repository: nginx/nginx
          path: './nginx'
          ref: ${{needs.fetch_tags.outputs.nginx_tag}}

      - id: step_checkout_more_module
        uses: actions/checkout@v2
        with:
          repository: openresty/headers-more-nginx-module
          path: './more_module'
          ref: ${{needs.fetch_tags.outputs.more_module_tag}}
      
      - id: build
        name: Build module
        run: |
          cd "$GITHUB_WORKSPACE/nginx"
          output_path="$GITHUB_WORKSPACE/nginx_output"
          ./auto/configure --prefix="$output_path" --add-dynamic-module=../more_module --with-compat
          make install
          
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/nginx_output

          echo "load_module modules/ngx_http_headers_more_filter_module.so;" >> /tmp/nginx.conf
          cat $output_path/conf/nginx.conf >> /tmp/nginx.conf
          sed -i "s/80;/8080;/g" /tmp/nginx.conf
          mv /tmp/nginx.conf $output_path/conf/
          cd $output_path/sbin
          ./nginx -t
          echo "module_path=$output_path/modules/ngx_http_headers_more_filter_module.so" >> "$GITHUB_OUTPUT"
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.fetch_tags.outputs.output_tag }}
          token: ${{ secrets.RELEASE_TOKEN }}
          body: |
            Nginx more headers module version: ${{needs.fetch_tags.outputs.more_module_tag}}
            Nginx version: ${{needs.fetch_tags.outputs.nginx_tag}}
          files: |
            ${{ steps.build.outputs.module_path }}
        
      - id: test_output
        name: Step to test output
        run: |
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/nginx_output/modules


          
    
